@file:Suppress("ktlint:standard:no-wildcard-imports", "WildcardImport")

package io.github.tulipltt.tulip.report

import kotlinx.html.*
import kotlinx.html.stream.appendHTML
import kotlinx.serialization.json.Json
import org.slf4j.LoggerFactory
import java.nio.file.Files
import java.nio.file.Paths

/**
 * Main generator for Tulip performance reports.
 */
object TulipReportGenerator {
    private val logger = LoggerFactory.getLogger(TulipReportGenerator::class.java)

    private val json =
        Json {
            ignoreUnknownKeys = true
        }

    /**
     * Generates a complete HTML report from the provided [ReportData].
     */
    fun generateHtml(reportData: ReportData): String {
        val out = StringBuilder()
        out.append("<!DOCTYPE html>\n")
        out.appendHTML().html {
            lang = "en"
            attributes["data-theme"] = "dark"
            head {
                meta { charset = "UTF-8" }
                title { +"Tulip Performance Report" }
                style { unsafe { +ReportStyles.picoCss } }
                style { unsafe { +ReportStyles.styles } }
                script { unsafe { +ReportScripts.echartsJs } }
                script { unsafe { +ReportScripts.scripts } }
            }
            body {
                div(classes = "loading-overlay") {
                    div(classes = "loading-spinner") {}
                    div(classes = "loading-text") { +"Loading..." }
                }
                val warnings = ReportDataValidator.validate(reportData)
                @Suppress("UNCHECKED_CAST")
                val groupedResults =
                    reportData.results.groupBy {
                        it.bmName ?: "Unknown Benchmark"
                    } as Map<String, List<BenchmarkResult>>
                renderSidebar(reportData, groupedResults.keys)
                main {
                    if (warnings.isNotEmpty()) {
                        article(classes = "warning-banner") {
                            header { strong { +"Data Integrity Warning" } }
                            ul {
                                warnings.forEach { li { +it } }
                            }
                        }
                    }
                    renderMainHeader(reportData, groupedResults)
                    renderOverviewSection(groupedResults)
                    renderBenchmarkDetails(groupedResults)
                    renderConfigAndRuntime(reportData)
                    footer(classes = "report-footer") {
                        val msg = "Generated by Tulip Performance Tool • ${reportData.timestamp}"
                        p { +msg }
                    }
                }
            }
        }
        return out.toString()
    }

    private fun FlowContent.renderSidebar(reportData: ReportData, benchmarkNames: Set<String>) {
        aside {
            id = "mySidebar"
            header {
                unsafe { +ReportLogos.LARGE }
                a(href = "https://tulipltt.github.io/Tulip-docs", target = "_blank", classes = "header-link") {
                    div(classes = "text-left") {
                        h5 { +"Tulip" }
                        small(classes = "opacity-50") {
                            +"${reportData.version}"
                        }
                    }
                }
            }
            nav {
                ul {
                    li { div(classes = "nav-section") { +"Overview" } }
                    renderNavLink("#overview", "Summary Dashboard", ReportIcons.DASHBOARD)
                    li { div(classes = "nav-section") { +"Benchmarks" } }
                    benchmarkNames.forEach { name ->
                        renderNavLink("#benchmark_${name.replace(" ", "_")}", name, ReportIcons.ACTIVITY)
                    }
                    li { div(classes = "nav-section") { +"Configuration" } }
                    renderNavLink("#config", "Benchmark Config", ReportIcons.SETTINGS)
                    renderNavLink("#runtime", "Tulip Runtime", ReportIcons.INFO)
                    li { div(classes = "nav-section") { +"Appearance" } }
                    li {
                        a(href = "#", classes = "theme-toggle nav-link") {
                            unsafe { +ReportIcons.THEME }
                            +"Toggle Theme"
                        }
                    }
                }
            }
        }
    }

    private fun UL.renderNavLink(
        href: String,
        label: String,
        icon: String,
    ) {
        li {
            a(href = href, classes = "nav-link") {
                unsafe { +icon }
                +label
            }
        }
    }

    private fun FlowContent.renderMainHeader(
        reportData: ReportData,
        groupedResults: Map<String, List<BenchmarkResult>>,
    ) {
        header {
            id = "header"
            div(classes = "container-fluid") {
                div(classes = "align-center flex-gap-1rem") {
                    style = "display: flex;" // Temporary until I check if Pico handles display:flex on align-center
                    //unsafe { +ReportLogos.LARGE }
                    div {
                        h2(classes = "m-0") { +"Performance Test Results" }
                        h5(classes = "m-0") { +"${reportData.config.actions.description}" }
                    }
                }
            }
            div(classes = "grid") {
                metricCard("Timestamp", reportData.timestamp)
                metricCard("Benchmarks", groupedResults.size.toString())
                val sumActions = reportData.results.sumOf { it.numActions?.toLong() ?: 0L }.toString()
                metricCard("Total Actions", sumActions)
                metricCard("Total Failed", reportData.results.sumOf { it.numFailed?.toLong() ?: 0L }.toString())
            }
        }
    }

    private fun FlowContent.renderOverviewSection(groupedResults: Map<String, List<BenchmarkResult>>) {
        div {
            id = "overview"
            statsCard(
                StatsCardConfig(
                    titleText = "All Benchmarks Summary",
                    classes = "full-width",
                    tableId = "summary_table",
                ),
            ) {
                summaryTable(groupedResults, "summary_table")
            }
        }
    }

    private fun FlowContent.renderBenchmarkDetails(groupedResults: Map<String, List<BenchmarkResult>>) {
        groupedResults.forEach { (bmName, results) ->
            val bmId = bmName.replace(" ", "_")
            section {
                id = "benchmark_$bmId"
                div(classes = "align-center flex-gap-1rem") {
                    style = "display: flex;"
                    h3(classes = "section-header m-0") { +"Benchmark: $bmName" }
                    a(href = "#config_$bmId", classes = "outline secondary p-0 m-0 font-08em") {
                        style = "padding: 2px 8px !important; border-radius: 4px;"
                        +"View Config"
                    }
                }
                statsCard(
                    StatsCardConfig(
                        titleText = "Benchmark Iterations: $bmName",
                        classes = "full-width",
                        tableId = "table_$bmId",
                    ),
                ) {
                    details {
                        style = "margin-top: 1rem;"
                        summary { +"Benchmark Iteration Details" }
                        detailedBenchmarkTable(results, "table_$bmId")
                    }
                }
                renderBenchmarkCharts(bmId, results)
            }
        }
    }

    private fun FlowContent.renderConfigAndRuntime(reportData: ReportData) {
        section {
            id = "config"
            h3(classes = "section-header") { +"Benchmark Configuration" }
            configSection(reportData.config)
        }
        section {
            id = "runtime"
            h3(classes = "section-header") { +"Tulip Runtime" }
            runtimeSection(reportData)
        }
    }

    private fun FlowContent.metricCard(
        label: String,
        value: String,
    ) {
        article(classes = "metric-card") {
            small { +label }
            strong { +value }
        }
    }

    /**
     * Entry point for creating both HTML and AsciiDoc reports.
     */
    fun createReport(
        jsonPath: String,
        htmlOutputPath: String,
    ) {
        val inputPath = Paths.get(jsonPath)
        if (!Files.exists(inputPath)) {
            logger.error("Input JSON file not found: $jsonPath")
            return
        }

        val outputPath = Paths.get(htmlOutputPath)
        outputPath.parent?.let { Files.createDirectories(it) }

        val jsonText = Files.readString(inputPath)
        val reportData = json.decodeFromString<ReportData>(jsonText)

        Files.writeString(outputPath, generateHtml(reportData))

        val adocPath = htmlOutputPath.replace(".html", "_c.adoc")
        Files.writeString(Paths.get(adocPath), ReportAdoc.generateAsciiDoc(reportData))

        ReportAdoc.convertAdocToHtml(adocPath)
    }
}

/**
 * SVG Logos for the Tulip brand.
 */
object ReportLogos {
    private val LOGO_SVG by lazy {
        ReportLogos::class.java.getResource("tulip_logo.svg")?.readText()
            ?: error("Resource tulip_logo.svg not found")
    }

    val SMALL by lazy { LOGO_SVG.replace("SIZE", "24") }
    val LARGE by lazy { LOGO_SVG.replace("SIZE", "48") }
}
