= Changelog
:toc: left
:sectnums:
:toclevels: 3

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

== [v2.1.0] - 2025-01-06

=== Release Notes

* Changed the contexts configuration section from a JSON array to a JSON map.
+
[source,json]
----
"contexts": {
    "Context-0": {
        "enabled": true,
        "num_users": 16,
        "num_threads": 2
    },
    "Context-1": {
        "enabled": false,
        "num_users": 32,
        "num_threads": 4
    }
}
----

* Changed the benchmarks configuration section from a JSON array to a JSON map.
+
[source,json]
----
"benchmarks": {
    "Init": {
        "enabled": true,
        "actions": [
            { "id": 0 }
        ]
    },
    "Max TPS": {
        "enabled": true,
        "throughput_rate": 0.0,
        "worker_thread_queue_size": 0,
        "time": {
            "pre_warmup_duration": 15,
            "warmup_duration": 30,
            "benchmark_duration": 60,
            "benchmark_repeat_count": 4
        },
        "workflow": "max-tps"
    },
    "Shutdown": {
        "enabled":true,
        "actions": [
            {"id": 99 }
        ]
    }
}
----


== [v2.0.5] - 2025-01-05

=== Release Notes

* Created a benchmark configuration report generated from <config-filename>.jsonc as <config-filename>.adoc

* Renamed JMM to MEM in performance report output

== [v2.0.4] - 2024-12-29

=== Release Notes

* Configuration files can either use JSON or JSONC content format. The latter is preferred.

* Updated the tulip-main benchmark test to use JSONC for its benchmark configuration file.

=== Release Information

Tulip is now available on Maven Central at:

* https://central.sonatype.com/namespace/io.github.wfouche.tulip
+
.Maven (xml)
[source,xml]
----
<dependency>
    <groupId>io.github.wfouche.tulip</groupId>
    <artifactId>tulip-runtime</artifactId>
    <version>2.0.4</version>
</dependency>
----
+
.Gradle (Groovy)
[source,groovy]
----
implementation 'io.github.wfouche.tulip:tulip-runtime:2.0.4'
----
+
.Gradle (kts)
[source,kotlin]
----
implementation("io.github.wfouche.tulip:tulip-runtime:2.0.4")
----


* Documentation:

** https://wfouche.github.io/Tulip/

== [v2.0.3] - 2024-12-22

=== Release Notes

* Renamed JSON benchmark configuration file section *static* to *actions*

* Implemented runtime support to read workflow definitions and build the corresponding Markov chain matrix from it

* The JSON benchmark configuration file now has four main sections:

** actions
** contexts
** benchmarks
** workflows

* Updated the tulip-main benchmark to use workflow definitions

=== Release Information

Tulip is now available on Maven Central at:

* https://central.sonatype.com/namespace/io.github.wfouche.tulip
+
.Maven (xml)
[source,xml]
----
<dependency>
    <groupId>io.github.wfouche.tulip</groupId>
    <artifactId>tulip-runtime</artifactId>
    <version>2.0.3</version>
</dependency>
----
+
.Gradle (Groovy)
[source,groovy]
----
implementation 'io.github.wfouche.tulip:tulip-runtime:2.0.3'
----
+
.Gradle (kts)
[source,kotlin]
----
implementation("io.github.wfouche.tulip:tulip-runtime:2.0.3")
----


* Documentation:

** https://wfouche.github.io/Tulip/

== [v2.0.2] - 2024-12-15

=== Release Notes

* Allow JSON primitive types to be specified for user parameters for action objects.
+
[source,json]
----
{
  "user_params": {
    "url": "http://localhost",
    "debug": false,
    "http_port": 7070
  }
}
----

* Use method `getProcessCpuTime` from class `OperatingSystemMXBean` to accurately determine the CPU utilization of Tulip.

* Display the current heap usage to the Tulip console in  GB and not bytes.

=== Release Information

Tulip is now available on Maven Central at:

* https://central.sonatype.com/namespace/io.github.wfouche.tulip
+
.Maven (xml)
[source,xml]
----
<dependency>
    <groupId>io.github.wfouche.tulip</groupId>
    <artifactId>tulip-runtime</artifactId>
    <version>2.0.2</version>
</dependency>
----
+
.Gradle (Groovy)
[source,groovy]
----
implementation 'io.github.wfouche.tulip:tulip-runtime:2.0.2'
----
+
.Gradle (kts)
[source,kotlin]
----
implementation("io.github.wfouche.tulip:tulip-runtime:2.0.2")
----


* Documentation:

** https://wfouche.github.io/Tulip/

== [v2.0.1] - 2024-12-08

=== Release Notes

==== TulipApi

* The `runTulip` method can now be invoked without providing a `TulipUserFactory` object. In special cases this might still be needed, so the old way of invoking Tulip continues to be supported.
+
.Simplified
[source,java]
----
package org.example;

import io.github.wfouche.tulip.api.*;

public class App {
    public static void main(String[] args) {
        TulipApi.runTulip("./benchmark_config.json");
    }
}
----
+
.Original
[source,java]
----
package org.example;

import io.github.wfouche.tulip.api.*;

public class App {
    public static void main(String[] args) {
        TulipApi.runTulip("./benchmark_config.json", new TulipUserFactory());
    }
}
----

==== TulipConsole

* Implemented method `put (List<String> list)` to print a list of Strings to the Tulip console (thread-safe output device).

=== Release Information

Tulip is now available on Maven Central at:

* https://central.sonatype.com/namespace/io.github.wfouche.tulip
+
.Maven (xml)
[source,xml]
----
<dependency>
    <groupId>io.github.wfouche.tulip</groupId>
    <artifactId>tulip-runtime</artifactId>
    <version>2.0.1</version>
</dependency>
----
+
.Gradle (Groovy)
[source,groovy]
----
implementation 'io.github.wfouche.tulip:tulip-runtime:2.0.1'
----
+
.Gradle (kts)
[source,kotlin]
----
implementation("io.github.wfouche.tulip:tulip-runtime:2.0.1")
----


* Documentation:

** https://wfouche.github.io/Tulip/

== [v2.0.0] - 2024-12-01

=== Release Notes

Tulip has been in development for five years. This is the first public release of the Tulip load testing framework.

=== Release Information

Tulip is now available on Maven Central at:

* https://central.sonatype.com/namespace/io.github.wfouche.tulip
+
.Maven (xml)
[source,xml]
----
<dependency>
    <groupId>io.github.wfouche.tulip</groupId>
    <artifactId>tulip-runtime</artifactId>
    <version>2.0.0</version>
</dependency>
----
+
.Gradle (Groovy)
[source,groovy]
----
implementation 'io.github.wfouche.tulip:tulip-runtime:2.0.0'
----
+
.Gradle (kts)
[source,kotlin]
----
implementation("io.github.wfouche.tulip:tulip-runtime:2.0.0")
----

* Documentation for Tulip is under development and will be available at the following website once completed:

  https://wfouche.github.io/Tulip/