= Developer Notes
:toc:
:sectnums:

== [DONE] [.line-through]#External Config via JSON File#

.config.json
[source,json]
----
{
    "json_filename": "json_results.txt",
    "contexts": [
        {
            "name": "Scenario-1",
            "num_users": 16,
            "num_threads": 2
        },
        {
            "name": "Scenario-2",
            "num_users": 32,
            "num_threads": 4
        }
    ],
    "benchmarks": [
        {
            "name": "Test0 (Initialize)",
            "enabled": true,
            "time": {
                "startup_duration": 0,
                "warmup_duration": 0,
                "main_duration": 0,
                "main_duration_repeat_count": 1
            },
            "throughput_rate": 0.0,
            "work_in_progress": 1,
            "actions": [
                {
                    "id": 0
                },
                {
                    "id": 7
                }
            ]
        },
        {
            "name": "Test1 (Throughput Test - Max)",
            "enabled": false,
            "time": {
                "startup_duration": 60,
                "warmup_duration": 60,
                "main_duration": 60,
                "main_duration_repeat_count": 1
            },
            "throughput_rate": 0.0,
            "work_in_progress": -1,
            "actions": [
                {
                    "id": 8
                }
            ]
        },
        {
            "name": "Test2 (Throughput Test - Fixed)",
            "enabled": true,
            "time": {
                "startup_duration": 15,
                "warmup_duration": 15,
                "main_duration": 60,
                "main_duration_repeat_count": 4
            },
            "throughput_rate": 100.0,
            "work_in_progress": 0,
            "actions": [
                {
                    "id": 1,
                    "weight": 25
                },
                {
                    "id": 2,
                    "weight": 75
                }
            ]
        }
    ]
}
----

== [DONE] [.line-through]#Runtime Configuration#

Add `--config` parameter to specify which `config.json` file to use.

* https://github.com/Kotlin/kotlinx-cli

== [DONE] [.line-through]#HttpClient vs OkHttp#

. Use HttpClient from Java 21, and remove support for OkHttp

** https://www.baeldung.com/java-httpclient-connection-management

. Remove unused and optional JAR dependencies

** http4k
** ....

== Tulip Documentation

Create a user guide for Tulip with Antora

* https://twitter.com/antoraproject

* https://www.baeldung.com/java-httpclient-connection-management

** -Djdk.httpclient.connectionPoolSize=1
** -Djdk.httpclient.keepalive.timeout=2

* https://openjdk.org/groups/net/httpclient/recipes.html

== Pkl Config Support

Write a config.pkl file to generate config.json

* https://pkl-lang.org/blog/introducing-pkl.html

== GraalVM native application

Build a native (exe) using GraalVM of a Tulip benchmark application

* https://www.graalvm.org/

== Docker Support

Create a Docker container of a Tulip benchmark application using Docker Compose

* https://docs.docker.com/compose/

== Tulip Runtime Library

Create a Maven Central hosted tulip-core.jar runtime library that can be imported by benchmark applications

* https://jenkov.com/tutorials/maven/publish-to-central-maven-repository.html

[source,xml]
----
<dependency>
    <groupId>io.github.wfouche</groupId>
    <artifactId>tulip-core</artifactId>
    <version>0.8.1</version>
</dependency>
----

== Java Benchmark Support

Allow benchmark user class to be written in Java or other JVM compatible languages. Add support for:

* [.line-through]#Kotlin#
* Java
* Scala

== Reimplement JSON output

Re-implement how the json_results.txt file is created. Only use a hierarchy of data classes and GSON to create the JSON output, or kotlinx

* https://www.baeldung.com/kotlin/data-class-json-serialize-default-values

[source,kotlin]
----
import kotlinx.serialization.Serializable
@Serializable
data class Car(val type: String, @EncodeDefault val color: String = "Blue")

val car = Car("Ford")
val jsonString = Json.encodeToString(car)
assertEquals("{\"type\":\"Ford\",\"color\":\"Blue\"}", jsonString)
----

* https://discuss.kotlinlang.org/t/request-for-built-in-tostring-json-true-for-data-classes-for-json-output/6720/2