= Developer Notes
:toc:
:sectnums:

== [DONE] [.line-through]#External Config via JSON File#

.config.json
[source,json]
----
{
    "json_filename": "json_results.txt",
    "contexts": [
        {
            "name": "Scenario-1",
            "num_users": 16,
            "num_threads": 2
        },
        {
            "name": "Scenario-2",
            "num_users": 32,
            "num_threads": 4
        }
    ],
    "benchmarks": [
        {
            "name": "Test0 (Initialize)",
            "enabled": true,
            "time": {
                "startup_duration": 0,
                "warmup_duration": 0,
                "main_duration": 0,
                "main_duration_repeat_count": 1
            },
            "throughput_rate": 0.0,
            "work_in_progress": 1,
            "actions": [
                {
                    "id": 0
                },
                {
                    "id": 7
                }
            ]
        },
        {
            "name": "Test1 (Throughput Test - Max)",
            "enabled": false,
            "time": {
                "startup_duration": 60,
                "warmup_duration": 60,
                "main_duration": 60,
                "main_duration_repeat_count": 1
            },
            "throughput_rate": 0.0,
            "work_in_progress": -1,
            "actions": [
                {
                    "id": 8
                }
            ]
        },
        {
            "name": "Test2 (Throughput Test - Fixed)",
            "enabled": true,
            "time": {
                "startup_duration": 15,
                "warmup_duration": 15,
                "main_duration": 60,
                "main_duration_repeat_count": 4
            },
            "throughput_rate": 100.0,
            "work_in_progress": 0,
            "actions": [
                {
                    "id": 1,
                    "weight": 25
                },
                {
                    "id": 2,
                    "weight": 75
                }
            ]
        }
    ]
}
----

== [DONE] [.line-through]#Runtime Configuration#

Add `--config` parameter to specify which `config.json` file to use.

* https://github.com/Kotlin/kotlinx-cli

== [DONE] [.line-through]#HttpClient vs OkHttp#

. Use HttpClient from Java 21, and remove support for OkHttp

** https://www.baeldung.com/java-httpclient-connection-management

. Remove unused and optional JAR dependencies

** http4k
** ....

== Tulip Documentation

Create a user guide for Tulip with Antora

* https://twitter.com/antoraproject

* https://www.baeldung.com/java-httpclient-connection-management

** -Djdk.httpclient.connectionPoolSize=1
** -Djdk.httpclient.keepalive.timeout=2

* https://openjdk.org/groups/net/httpclient/recipes.html

== [DROPPED] [.line-through]#Pkl Config Support#

Write a config.pkl file to generate config.json

* https://pkl-lang.org/blog/introducing-pkl.html

== GraalVM native application

Build a native (exe) using GraalVM of a Tulip benchmark application

* https://www.graalvm.org/

[source,bash]
----
$ ./gradlew nativeCompile

$ ./build/native/nativeCompile/tulip -c ./config.json
----

* https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html

== Docker Support

Create a Docker container of a Tulip benchmark application using Docker Compose

* https://docs.docker.com/compose/

== Tulip Runtime Library

Create a Maven Central hosted tulip-core.jar runtime library that can be imported by benchmark applications

* https://jenkov.com/tutorials/maven/publish-to-central-maven-repository.html

[source,xml]
----
<dependency>
    <groupId>io.github.wfouche</groupId>
    <artifactId>tulip-core</artifactId>
    <version>0.8.1</version>
</dependency>
----

== [DONE] [.line-through]#Java Benchmark Support#

Allow benchmark user class to be written in Java or other JVM compatible languages. Add support for:

* [.line-through]#Kotlin#
* [.line-through]#Java#

== Reimplement JSON input (config.json)

Use Kotlin Serialization instead of GSON:

* Support JSON5 format
* Support GraalVM

== Reimplement JSON output

Re-implement how the json_results.txt file is created. Only use a hierarchy of data classes and GSON to create the JSON output, or kotlinx

* https://www.baeldung.com/kotlin/data-class-json-serialize-default-values

[source,kotlin]
----
import kotlinx.serialization.Serializable
@Serializable
data class Car(val type: String, @EncodeDefault val color: String = "Blue")

val car = Car("Ford")
val jsonString = Json.encodeToString(car)
assertEquals("{\"type\":\"Ford\",\"color\":\"Blue\"}", jsonString)
----

* https://discuss.kotlinlang.org/t/request-for-built-in-tostring-json-true-for-data-classes-for-json-output/6720/2

== [DONE] [.line-through]#Micrometer Support#

Instrument the benchmark application using Micrometer (http://micrometer.io) and support performance data extraction via Prometheus and Grafana.

* https://grafana.com/docs/grafana/latest/getting-started/get-started-grafana-prometheus/

* $ docker run --name prometheus -d -p 127.0.0.1:9090:9090 prom/prometheus

* https://wfouche.grafana.net/a/cloud-home-app/onboarding-flow/start
* https://grafana.com/docs/grafana-cloud/send-data/metrics/metrics-prometheus/prometheus-config-examples/pivotal-software-inc-micrometer/

Also see `docker compose` scripts at:

* https://github.com/docker/awesome-compose/blob/master/prometheus-grafana/README.md

== [DONE] [.line-through]#Amper Support#

Change the Tulip project to build using Amper/Gradle.

* https://blog.jetbrains.com/blog/2023/11/09/amper-improving-the-build-tooling-user-experience/

== [DONE] [.line-through]#Remove Glowroot support#

Remove folder `tulip/runtime/glowroot`.

See https://glowroot.org/ and https://github.com/glowroot/glowroot

== [DONE] [.line-through]#Add user_actions and user_class to config.json#

[source,yaml]
----
{
    "user_class": "user.UserHttp",
    "user_actions": {
        "0": "start",
        "1": "DELAY-6ms",
        "2": "DELAY-14ms",
        "3": "REST-posts",
        "4": "REST-comments",
        "5": "REST-albums",
        "6": "REST-photos",
        "7": "REST-todos",
        "8": "login",
        "99": "stop"
    }
}
----

== [DONE] [.line-through]#Add user_params to config.json#

[source,json]
----
{
    ....
    "user_params": {
        "url": "https://jsonplaceholder.typicode.com",
        ....
    },
    ....
}
----

== [DONE] [.line-through]#Re-write tulip_user.py in Kotlin Script#

* tulip_user.py
* tulip_user.kts

== Re-write json_print_asciidoc.py in Kotlin Script

* json_print_asciidoc.py
* json_print_asciidoc.kts

== Benchmark Summary

Display a summary of benchmark results at the end of the benchmark:

Benchmark1::
* Name
* Average TPS
* Average response time
* 90th percentile
* Max response time
* Num-failed nnn (%xyz)

Benchmark2::
* Name
* Average TPS
* Average response time
* 90th percentile
* Max response time
* Num-failed nnn (%xyz)

Benchmark...::
* Name
* Average TPS
* Average response time
* 90th percentile
* Max response time
* Num-failed nnn (%xyz)

== Performance Requirements

[source,json]
----
{
    "performance_requirements": {
        "avg-tps": "12 tps",
        "avg-tps-variance": "10 percent",
        ...
    }
}
----

== HdrHistogram

Use https://hdrhistogram.github.io/HdrHistogram/[HdrHistogram] to replace Tulip's own log-linear quantization logic.

HdrHistogram is a standard used by several load testing tools.

* implementation("org.hdrhistogram:HdrHistogram:2.2.2")
* https://github.com/Hyperfoil/Hyperfoil uses HdrHistogram

[source,java]
----
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.hdrhistogram:HdrHistogram:2.2.2

import org.HdrHistogram.Histogram;

import java.util.concurrent.ThreadLocalRandom;

public class test_hdrhistogram {
    public static void main(String[] args) {
        //Histogram histogram = new Histogram(3600*1000*1000L, 3);
        Histogram histogram = new Histogram(3);

        // 6 ms delay (average) with 25% of values
        for (int i=0; i != 250000; i++) {
            histogram.recordValue(ThreadLocalRandom.current().nextLong(12 + 1));
        }

        // 14 ms delay (average) with 75% of values
        for (int i=0; i != 750000; i++) {
            histogram.recordValue(ThreadLocalRandom.current().nextLong(28 + 1));
        }
        // histogram.getMean() = 12.0

        System.out.println(histogram.getTotalCount());
        histogram.outputPercentileDistribution(System.out,1.0);
        System.out.println(histogram.getMean());
        System.out.println(histogram.getStdDeviation());
        System.out.println(histogram.getMaxValue());
        System.out.println(histogram.getValueAtPercentile(50.0));
        System.out.println(histogram.getValueAtPercentile(90.0));
        System.out.println(histogram.getValueAtPercentile(95.0));
        System.out.println(histogram.getValueAtPercentile(99.0));
        System.out.println(histogram.getValueAtPercentile(99.9));
    }
}
----

== Summary Statistics


----
PHASE    METRIC  THROUGHPUT    ACTIONS  MEAN      STD_DEV  p50       p90       p99       p99.9     MAX        SUCCESS   FAILED
example  test    29,41 req/s         1  17,37 ms     0 ms  17,43 ms  17,43 ms  17,43 ms  17,43 ms  17,43 ms         1        0
----

== JCTools Concurrent Queues

Replace queues in JC queues.

* https://github.com/JCTools/JCTools

== kscript

Remove kscript, kotlin 1.9.24 and use jbang

== [DONE] [.line-through]#Total Time Blocked#

Add a counter that records the total time that the main thread is blocked waiting to assigned tasks to worker threads.

* https://medium.com/@siddontang/the-coordinated-omission-problem-in-the-benchmark-tools-5d9abef79279

* http://btw2017.informatik.uni-stuttgart.de/slidesandpapers/E4-11-107/paper_web.pdf

== [DONE] [.line-through]#Add histogram_rt data to results file#

[source,json]
----
{
    "histogram_rt": {
      "10000": 839,
      "20000": 745,
      "3000": 284,
      "30000": 175,
      "15000": 792,
      "10": 95,
      "5000": 247,
      "25000": 815,
      "2000": 242,
      "15": 121,
      "8000": 259,
      "9000": 277,
      "7000": 247,
      "4000": 273,
      "6000": 261,
      "1000": 267,
      "5": 3,
      "50": 1,
      "20": 33,
      "6500": 1,
      "9": 12,
      "1500": 1,
      "8": 4,
      "6": 1,
      "7": 3,
      "9500": 3,
      "3500": 1,
      "25": 3,
      "2500": 1,
      "8500": 1,
      "4500": 1,
      "5500": 1,
      "7500": 1,
      "4": 1,
      "30": 1
    }
}
----

== [DONE] [.line-through]#Coordinaton Ommision Problem#

Measure the wait time for each action, and add it to the service time.

* https://redhatperf.github.io/post/coordinated-omission/