= Tulip (The Ultimate Load Injection Program)
:sectnums:
:toc:

== Dependencies

Install Git and JDK21 before building Tulip from source.

=== Linux

Install SDKMAN from bash (https://sdkman.io)
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

Install `w3m` (Debian, Ubuntu) to display reports
----
$ sudo apt install w3m
----

=== MacOS

Install SDKMAN from zsh or bash (https://sdkman.io)
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

Install `w3m` (MacOS) to display reports
----
$ brew install w3m
----

=== Windows

Open a Windows PowerShell (PS) terminal (version 5.1 or later) and from the PS `C:\>` prompt, run:

.Step 1 - run Set-ExecutionPolicy
----
PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
----
.Step 2 - answer 'Y' when prompted to change the execution policy.
----
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\>
----

.Step 3 - run Invoke-RestMethod
----
PS C:\> Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
----

.Step 4 - wait for the installation to finish
----
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\>
----

Install Git and Git-Bash

[source,cmd]
----
scoop install git
----

Install MS Java 21 (OpenJDK)
----
scoop bucket add java
----

----
scoop install microsoft21-jdk
----

(Optionally) Install WinGetUI (aka UniGetUI) to apply future updates to the installed applications
----
scoop bucket add extras
----
----
scoop install extras/wingetui
----

== Build from Source

=== Linux

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh  or ./build_and_run.sh --args="--config config.json"
----

=== MacOS

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== Windows

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
build_and_run.cmd
----

== Example Benchmark Report

[source,text,options=nowrap]
----
Benchmark Report

SID         Name         RID Duration    #N       #S    #F  Avg TPS    Avg RT   Sdv RT  90p RT   99p RT   Max RT      Max RT Timestamp
0   Init (u:16 t:2)
                         0   0.026    32       32       0  1230.8    0.120 ms   0.5 ms 0.0 ms   2.6 ms   2.6 ms   2024-07-10 11:49:02.337
                         -   0:00:00  32       32       0  1230.8    0.120 ms   0.4 ms 0.0 ms   2.6 ms   2.6 ms   2024-07-10 11:49:02.337
0   Max TPS (u:16 t:2)
                         0   60.0     82784637 82784637 0  1379743.9 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-10 11:52:00.464
                         -   0:01:00  82784637 82784637 0  1379743.9 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-10 11:52:00.464
0   Fixed TPS (u:16 t:2)
                         0   60.0     5996     5996     0  99.9      12.094 ms  8.2 ms 25.2 ms  28.3 ms  28.3 ms  2024-07-10 11:53:37.824
                         1   60.0     6000     6000     0  100.0     12.163 ms  8.3 ms 25.2 ms  28.3 ms  28.2 ms  2024-07-10 11:54:01.190
                         2   60.0     6001     6001     0  100.0     12.256 ms  8.3 ms 25.2 ms  28.3 ms  28.3 ms  2024-07-10 11:55:05.135
                         3   60.0     5996     5996     0  99.9      12.219 ms  8.2 ms 25.2 ms  28.3 ms  28.3 ms  2024-07-10 11:56:19.135
                         -   0:04:00  23993    23993    0  100.0     12.153 ms  8.2 ms 25.1 ms  28.2 ms  28.3 ms  2024-07-10 11:53:37.824
0   HTTP (u:16 t:2)
                         0   30.0     44999    44999    0  1500.0    0.575 ms   0.2 ms 0.7 ms   0.9 ms   16.6 ms  2024-07-10 11:57:21.206
                         1   30.0     45001    45001    0  1500.0    0.537 ms   0.2 ms 0.7 ms   0.8 ms   15.3 ms  2024-07-10 11:58:08.097
                         2   30.0     45003    45003    0  1500.1    0.573 ms   0.2 ms 0.7 ms   0.8 ms   16.0 ms  2024-07-10 11:58:26.900
                         -   0:01:30  135003   135003   0  1500.0    0.560 ms   0.2 ms 0.7 ms   0.8 ms   16.6 ms  2024-07-10 11:57:21.206
0   Shutdown (u:16 t:2)
                         0   1.608    16       16       0  10.0      100.160 ms 0.2 ms 100.4 ms 101.4 ms 101.3 ms 2024-07-10 11:58:52.785
                         -   0:00:01  16       16       0  10.0      99.936 ms  0.2 ms 99.9 ms  100.9 ms 101.3 ms 2024-07-10 11:58:52.785

----

== Appendix

=== Coordinated Omission

Tulip compensates for back-pressure from the system under test and adjusts the measured service times accordingly:

* https://redhatperf.github.io/post/coordinated-omission/

=== Kotlin Books

* https://www.manning.com/books/kotlin-in-action[Kotlin in Action, 1st Edition]
* https://typealias.com/start/[Kotlin: An Illustrated Guide]

=== Performance Engineering

* "Stop Rate Limiting! Capacity Management Done Right" by Jon Moore
** https://www.youtube.com/watch?v=m64SWl9bfvk
