= Tulip (The Ultimate Load Injection Program)
:sectnums:
:toc:

== Dependencies

Install Git and JDK21 before building Tulip from source.

=== Linux

Install SDKMAN from bash
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

=== MacOS

Install SDKMAN from zsh or bash
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

=== Windows

Open a Windows PowerShell (PS) terminal (version 5.1 or later) and from the PS `C:\>` prompt, run:

.Step 1 - run Set-ExecutionPolicy
----
PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
----
.Step 2 - answer 'Y' when prompted to change the execution policy.
----
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\>
----

.Step 3 - run Invoke-RestMethod
----
PS C:\> Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
----

.Step 4 - wait for the installation to finish
----
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\>
----

Install Git and Git-Bash

[source,cmd]
----
scoop install git
----

Install MS Java 21 (OpenJDK)
----
scoop bucket add java
----

----
scoop install microsoft21-jdk
----

(Optionally) Install WinGetUI (aka UniGetUI) to apply future updates to the installed applications
----
scoop bucket add extras
----
----
scoop install extras/wingetui
----

== Build from Source

=== Linux

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== MacOS

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== Windows

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
build_and_run.cmd
----

== Example Benchmark Report

[source,text,options=nowrap]
----
Benchmark Report

SID       Name       RID Duration    #T       #S    #F  Avg TPS    Avg RT   Sdv RT   90p RT   99p RT   Max RT      Max RT Timestamp
    Init
0   users = 16
    threads = 2
                     0   0.032    32       32       0  1000.0    0.129 ms   0.4 ms  0.1 ms   2.5 ms   2.5 ms   2024-07-08 12:10:18.680
                     -   0:00:00  32       32       0  1000.0    0.128 ms   0.4 ms  0.1 ms   2.5 ms   2.5 ms   2024-07-08 12:10:18.680
    Max Throughput
0   users = 16
    threads = 2
                     0   60.0     81919921 81919921 0  1365332.0 0.000 ms   0.0 ms  0.0 ms   0.0 ms   0.1 ms   2024-07-08 12:13:17.830
                     -   0:01:00  81919921 81919921 0  1365332.0 0.000 ms   0.0 ms  0.0 ms   0.0 ms   0.1 ms   2024-07-08 12:13:17.830
    Fixed Throughput
0   users = 16
    threads = 2
                     0   60.005   6007     6007     0  100.1     12.204 ms  8.3 ms  25.2 ms  28.3 ms  28.3 ms  2024-07-08 12:14:20.832
                     1   60.008   6008     6008     0  100.1     12.326 ms  8.4 ms  25.2 ms  28.3 ms  28.3 ms  2024-07-08 12:15:18.555
                     2   60.005   6010     6010     0  100.2     12.152 ms  8.3 ms  25.2 ms  28.3 ms  28.2 ms  2024-07-08 12:16:16.465
                     3   60.026   6012     6012     0  100.2     12.209 ms  8.2 ms  25.2 ms  28.3 ms  28.2 ms  2024-07-08 12:17:58.337
                     -   0:04:00  24037    24037    0  100.1     12.193 ms  8.3 ms  25.1 ms  28.2 ms  28.3 ms  2024-07-08 12:15:18.555
    HTTP
0   users = 16
    threads = 2
                     0   30.2     149      149      0  4.9       34.393 ms  4.7 ms  37.6 ms  55.6 ms  70.3 ms  2024-07-08 12:18:45.817
                     1   30.003   150      150      0  5.0       34.780 ms  4.0 ms  40.7 ms  48.9 ms  53.2 ms  2024-07-08 12:19:20.816
                     2   30.196   153      153      0  5.1       36.882 ms  18.0 ms 41.2 ms  102.4 ms 237.3 ms 2024-07-08 12:19:34.820
                     -   0:01:30  452      452      0  5.0       35.270 ms  11.1 ms 38.9 ms  55.3 ms  237.3 ms 2024-07-08 12:19:34.820
    Shutdown
0   users = 16
    threads = 2
                     0   1.609    16       16       0  9.9       100.192 ms 0.3 ms  100.9 ms 101.4 ms 100.9 ms 2024-07-08 12:20:09.131
                     -   0:00:01  16       16       0  9.9       99.968 ms  0.3 ms  100.4 ms 100.9 ms 100.9 ms 2024-07-08 12:20:09.131

----

== Appendix

=== Coordinated Omission

Tulip compensates for back-pressure from the system under test and adjusts the measured service times accordingly:

* https://redhatperf.github.io/post/coordinated-omission/

=== Kotlin Books

* https://www.manning.com/books/kotlin-in-action[Kotlin in Action, 1st Edition]
* https://typealias.com/start/[Kotlin: An Illustrated Guide]

=== Performance Engineering

* "Stop Rate Limiting! Capacity Management Done Right" by Jon Moore
** https://www.youtube.com/watch?v=m64SWl9bfvk