= Tulip (The Ultimate Load Injection Program)
:sectnums:
:toc:

== Dependencies

Install Git and JDK21 before building Tulip from source.

=== Linux

Install SDKMAN from bash
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

=== MacOS

Install SDKMAN from zsh or bash
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

=== Windows

Open a Windows PowerShell (PS) terminal (version 5.1 or later) and from the PS `C:\>` prompt, run:

.Step 1 - run Set-ExecutionPolicy
----
PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
----
.Step 2 - answer 'Y' when prompted to change the execution policy.
----
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\>
----

.Step 3 - run Invoke-RestMethod
----
PS C:\> Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
----

.Step 4 - wait for the installation to finish
----
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\>
----

Install Git and Git-Bash

[source,cmd]
----
scoop install git
----

Install MS Java 21 (OpenJDK)
----
scoop bucket add java
----

----
scoop install microsoft21-jdk
----

(Optionally) Install WinGetUI (aka UniGetUI) to apply future updates to the installed applications
----
scoop bucket add extras
----
----
scoop install extras/wingetui
----

== Build from Source

=== Linux

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== MacOS

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== Windows

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
build_and_run.cmd
----

== Example Benchmark Report

[source,text,options=nowrap]
----
SID         Name         RID Duration    #N       #S    #F  Avg TPS    Avg RT   Sdv RT  90p RT   99p RT   Max RT      Max RT Timestamp
0   Init (u:16 t:2)
                         0   0.028    32       32       0  1142.9    0.145 ms   0.6 ms 0.1 ms   3.6 ms   3.5 ms   2024-07-08 14:05:21.981
                         -   0:00:00  32       32       0  1142.9    0.145 ms   0.6 ms 0.1 ms   3.5 ms   3.5 ms   2024-07-08 14:05:21.981
0   Max TPS (u:16 t:2)
                         0   60.0     80510105 80510105 0  1341835.1 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.3 ms   2024-07-08 14:07:56.842
                         -   0:01:00  80510105 80510105 0  1341835.1 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.3 ms   2024-07-08 14:07:56.842
0   Fixed TPS (u:16 t:2)
                         0   60.01    6008     6008     0  100.1     12.176 ms  8.3 ms 25.2 ms  28.3 ms  28.3 ms  2024-07-08 14:09:23.473
                         1   60.004   6010     6010     0  100.2     12.202 ms  8.3 ms 25.2 ms  28.3 ms  28.3 ms  2024-07-08 14:10:24.687
                         2   60.017   6010     6010     0  100.1     12.143 ms  8.2 ms 25.2 ms  28.3 ms  28.2 ms  2024-07-08 14:11:11.876
                         3   60.016   6011     6011     0  100.2     12.144 ms  8.3 ms 25.2 ms  28.3 ms  28.2 ms  2024-07-08 14:12:38.170
                         -   0:04:00  24039    24039    0  100.1     12.137 ms  8.3 ms 25.1 ms  28.2 ms  28.3 ms  2024-07-08 14:09:23.473
0   HTTP (u:16 t:2)
                         0   30.0     45145    45145    0  1504.8    0.677 ms   0.2 ms 0.8 ms   1.1 ms   17.0 ms  2024-07-08 14:14:00.460
                         1   30.002   45144    45144    0  1504.7    0.682 ms   0.2 ms 0.8 ms   1.1 ms   18.1 ms  2024-07-08 14:14:28.531
                         2   30.001   45151    45151    0  1505.0    0.680 ms   0.2 ms 0.8 ms   1.1 ms   17.4 ms  2024-07-08 14:14:47.218
                         -   0:01:30  135440   135440   0  1504.8    0.678 ms   0.2 ms 0.8 ms   1.1 ms   18.1 ms  2024-07-08 14:14:28.531
0   Shutdown (u:16 t:2)
                         0   1.609    16       16       0  9.9       100.192 ms 0.3 ms 100.9 ms 101.4 ms 101.3 ms 2024-07-08 14:15:12.222
                         -   0:00:01  16       16       0  9.9       99.968 ms  0.3 ms 100.4 ms 100.9 ms 101.3 ms 2024-07-08 14:15:12.222

----

== Appendix

=== Coordinated Omission

Tulip compensates for back-pressure from the system under test and adjusts the measured service times accordingly:

* https://redhatperf.github.io/post/coordinated-omission/

=== Kotlin Books

* https://www.manning.com/books/kotlin-in-action[Kotlin in Action, 1st Edition]
* https://typealias.com/start/[Kotlin: An Illustrated Guide]

=== Performance Engineering

* "Stop Rate Limiting! Capacity Management Done Right" by Jon Moore
** https://www.youtube.com/watch?v=m64SWl9bfvk