= Tulip (The Ultimate Load Injection Program)
:sectnums:
:toc:

== Dependencies

Install Git and JDK21 before building Tulip from source.

=== Linux

Install SDKMAN from bash (https://sdkman.io)
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

Install `w3m` (Debian, Ubuntu) to display reports
----
$ sudo apt install w3m
----

=== MacOS

Install SDKMAN from zsh or bash (https://sdkman.io)
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

Install `w3m` (MacOS) to display reports
----
$ brew install w3m
----

=== Windows

Open a Windows PowerShell (PS) terminal (version 5.1 or later) and from the PS `C:\>` prompt, run:

.Step 1 - run Set-ExecutionPolicy
----
PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
----
.Step 2 - answer 'Y' when prompted to change the execution policy.
----
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\>
----

.Step 3 - run Invoke-RestMethod
----
PS C:\> Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
----

.Step 4 - wait for the installation to finish
----
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\>
----

Install Git and Git-Bash

[source,cmd]
----
scoop install git
----

Install MS Java 21 (OpenJDK)
----
scoop bucket add java
----

----
scoop install microsoft21-jdk
----

(Optionally) Install WinGetUI (aka UniGetUI) to apply future updates to the installed applications
----
scoop bucket add extras
----
----
scoop install extras/wingetui
----

== Build from Source

=== Linux

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh  or ./build_and_run.sh --args="--config config.json"
----

=== MacOS

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== Windows

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
build_and_run.cmd
----

== Example Benchmark Reports

=== HTTP and other benchmarks

[source,text,options=nowrap]
----
SID          Name          RID  Avg TPS  Duration    #N        #S     #F   Avg RT   Stdev   90p RT   99p RT   Max RT      Max RT Timestamp
0   Init (u:16 t:2)
                           0   1280.0    0.025    32        32        0  0.137 ms   0.5 ms 0.1 ms   3.1 ms   3.1 ms   2024-07-15 11:59:34.103
                           -   1280.0    0:00:00  32        32        0  0.137 ms   0.5 ms 0.1 ms   3.1 ms   3.1 ms   2024-07-15 11:59:34.103
0   Max TPS-a (u:16 t:2)
                           0   1673120.6 30.0     50193618  50193618  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-15 12:00:45.350
                           1   1570599.0 30.0     47117970  47117970  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.2 ms   2024-07-15 12:00:55.325
                           2   1657730.9 30.0     49731926  49731926  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-15 12:01:54.157
                           -   1633816.8 0:01:30  147043514 147043514 0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.2 ms   2024-07-15 12:00:55.325
0   Max TPS-b (u:16 t:2)
                           0   1000000.0 30.0     30000000  30000000  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-15 12:02:49.460
                           1   1000000.0 30.0     30000000  30000000  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-15 12:03:39.991
                           2   1000000.0 30.0     30000000  30000000  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-15 12:04:10.798
                           -   1000000.0 0:01:30  90000000  90000000  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-15 12:02:49.460
0   Fixed TPS-a (u:16 t:2)
                           0   100.0     30.0     3001      3001      0  12.087 ms  8.4 ms 25.2 ms  28.3 ms  28.3 ms  2024-07-15 12:05:12.610
                           1   100.0     30.0     3001      3001      0  12.275 ms  8.2 ms 24.3 ms  28.2 ms  28.2 ms  2024-07-15 12:05:37.665
                           2   100.0     30.0     3001      3001      0  12.200 ms  8.3 ms 25.2 ms  28.3 ms  30.3 ms  2024-07-15 12:05:49.333
                           3   100.0     30.0     3001      3001      0  12.009 ms  8.1 ms 24.3 ms  28.3 ms  28.3 ms  2024-07-15 12:06:23.785
                           -   100.0     0:02:00  12004     12004     0  12.113 ms  8.2 ms 24.2 ms  28.2 ms  30.3 ms  2024-07-15 12:05:49.333
0   Fixed TPS-b (u:16 t:2)
                           0   100.0     30.0     3001      3001      0  10.169 ms  0.0 ms 10.2 ms  10.3 ms  10.5 ms  2024-07-15 12:07:38.919
                           1   100.0     30.0     3001      3001      0  10.163 ms  0.0 ms 10.2 ms  10.3 ms  10.4 ms  2024-07-15 12:08:18.917
                           2   100.0     30.0     3001      3001      0  10.167 ms  0.0 ms 10.2 ms  10.3 ms  10.3 ms  2024-07-15 12:08:46.763
                           3   100.0     30.0     3001      3001      0  10.165 ms  0.0 ms 10.2 ms  10.3 ms  10.4 ms  2024-07-15 12:09:03.980
                           -   100.0     0:02:00  12004     12004     0  10.138 ms  0.0 ms 10.2 ms  10.2 ms  10.5 ms  2024-07-15 12:07:38.919
0   HTTP-a (u:16 t:2)
                           0   10069.2   30.0     302075    302075    0  0.194 ms   0.0 ms 0.2 ms   0.3 ms   2.3 ms   2024-07-15 12:09:59.849
                           1   10003.0   30.0     300090    300090    0  0.196 ms   0.0 ms 0.2 ms   0.3 ms   3.1 ms   2024-07-15 12:10:29.476
                           2   9995.9    30.0     299877    299877    0  0.196 ms   0.0 ms 0.2 ms   0.3 ms   3.9 ms   2024-07-15 12:10:59.479
                           -   10022.7   0:01:30  902042    902042    0  0.195 ms   0.0 ms 0.2 ms   0.3 ms   3.9 ms   2024-07-15 12:10:59.479
0   HTTP-b (u:16 t:2)
                           0   1250.1    30.0     37502     37502     0  0.663 ms   0.1 ms 0.8 ms   0.9 ms   3.0 ms   2024-07-15 12:12:14.426
                           1   1250.1    30.0     37502     37502     0  0.652 ms   0.1 ms 0.8 ms   0.9 ms   3.2 ms   2024-07-15 12:12:59.311
                           2   1250.0    30.0     37500     37500     0  0.656 ms   0.1 ms 0.8 ms   0.9 ms   3.1 ms   2024-07-15 12:13:10.593
                           -   1250.0    0:01:30  112504    112504    0  0.655 ms   0.1 ms 0.8 ms   0.9 ms   3.2 ms   2024-07-15 12:12:59.311
0   Shutdown (u:16 t:2)
                           0   9.9       1.609    16        16        0  100.224 ms 0.4 ms 100.9 ms 101.7 ms 101.7 ms 2024-07-15 12:13:39.655
                           -   9.9       0:00:01  16        16        0  100.000 ms 0.4 ms 100.4 ms 101.4 ms 101.7 ms 2024-07-15 12:13:39.655

----

== Appendix

=== Coordinated Omission

Tulip compensates for back-pressure from the system under test and adjusts the measured service times accordingly:

* https://redhatperf.github.io/post/coordinated-omission/

=== Kotlin Books

* https://www.manning.com/books/kotlin-in-action[Kotlin in Action, 1st Edition]
* https://typealias.com/start/[Kotlin: An Illustrated Guide]

=== Performance Engineering

* "Stop Rate Limiting! Capacity Management Done Right" by Jon Moore
** https://www.youtube.com/watch?v=m64SWl9bfvk
