= Tulip (The Ultimate Load Injection Program)
:sectnums:
:toc:

== Dependencies

Install Git and JDK21 before building Tulip from source.

=== Linux

Install SDKMAN from bash
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

=== MacOS

Install SDKMAN from zsh or bash
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

=== Windows

Open a Windows PowerShell (PS) terminal (version 5.1 or later) and from the PS `C:\>` prompt, run:

.Step 1 - run Set-ExecutionPolicy
----
PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
----
.Step 2 - answer 'Y' when prompted to change the execution policy.
----
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\>
----

.Step 3 - run Invoke-RestMethod
----
PS C:\> Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
----

.Step 4 - wait for the installation to finish
----
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\>
----

Install Git and Git-Bash

[source,cmd]
----
scoop install git
----

Install MS Java 21 (OpenJDK)
----
scoop bucket add java
----

----
scoop install microsoft21-jdk
----

(Optionally) Install WinGetUI (aka UniGetUI) to apply future updates to the installed applications
----
scoop bucket add extras
----
----
scoop install extras/wingetui
----

== Build from Source

=== Linux

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== MacOS

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== Windows

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
build_and_run.cmd
----

== Example Benchmark Report

[source,text,options=nowrap]
----
Benchmark Report

SID       Name       RID Duration    #T       #S    #F  Avg TPS    Avg RT   Sdv RT   90p RT   99p RT   Max RT      Max RT Timestamp
0   Init
                     0   0.029    32       32       0  1103.4    0.136 ms   0.5 ms  0.0 ms   2.7 ms   2.7 ms   2024-07-08 11:24:24.920
                     -   0:00:00  32       32       0  1103.4    0.136 ms   0.5 ms  0.0 ms   2.7 ms   2.7 ms   2024-07-08 11:24:24.920
0   Max Throughput
                     0   60.0     79728117 79728117 0  1328801.9 0.000 ms   0.0 ms  0.0 ms   0.0 ms   0.3 ms   2024-07-08 11:26:54.851
                     -   0:01:00  79728117 79728117 0  1328801.9 0.000 ms   0.0 ms  0.0 ms   0.0 ms   0.3 ms   2024-07-08 11:26:54.851
0   Fixed Throughput
                     0   60.023   6008     6008     0  100.1     12.063 ms  8.2 ms  24.3 ms  28.3 ms  28.3 ms  2024-07-08 11:28:58.065
                     1   60.003   6010     6010     0  100.2     11.936 ms  8.2 ms  24.3 ms  28.3 ms  28.3 ms  2024-07-08 11:30:01.216
                     2   60.007   6002     6002     0  100.0     12.027 ms  8.1 ms  24.3 ms  28.3 ms  28.3 ms  2024-07-08 11:31:04.925
                     3   60.033   6013     6013     0  100.2     12.185 ms  8.3 ms  25.2 ms  28.3 ms  28.3 ms  2024-07-08 11:31:39.739
                     -   0:04:00  24033    24033    0  100.1     12.024 ms  8.2 ms  24.2 ms  28.2 ms  28.3 ms  2024-07-08 11:31:39.739
0   HTTP
                     0   30.001   148      148      0  4.9       35.472 ms  5.5 ms  38.7 ms  48.1 ms  91.4 ms  2024-07-08 11:32:59.649
                     1   30.198   151      151      0  5.0       35.964 ms  11.5 ms 40.2 ms  47.1 ms  171.0 ms 2024-07-08 11:33:30.047
                     2   30.0     152      152      0  5.1       34.902 ms  3.2 ms  39.4 ms  44.0 ms  49.0 ms  2024-07-08 11:33:58.447
                     -   0:01:30  451      451      0  5.0       35.344 ms  7.6 ms  39.2 ms  46.9 ms  171.0 ms 2024-07-08 11:33:30.047
0   Shutdown
                     0   1.608    16       16       0  10.0      100.160 ms 0.2 ms  100.4 ms 101.4 ms 101.3 ms 2024-07-08 11:34:15.169
                     -   0:00:01  16       16       0  10.0      99.936 ms  0.2 ms  99.9 ms  100.9 ms 101.3 ms 2024-07-08 11:34:15.169

----

== Appendix

=== Coordinated Omission

Tulip compensates for back-pressure from the system under test and adjusts the measured service times accordingly:

* https://redhatperf.github.io/post/coordinated-omission/

=== Kotlin Books

* https://www.manning.com/books/kotlin-in-action[Kotlin in Action, 1st Edition]
* https://typealias.com/start/[Kotlin: An Illustrated Guide]

=== Performance Engineering

* "Stop Rate Limiting! Capacity Management Done Right" by Jon Moore
** https://www.youtube.com/watch?v=m64SWl9bfvk