= Tulip (The Ultimate Load Injection Program)
:sectnums:
:toc:

== Dependencies

Install Git and JDK21 before building Tulip from source.

=== Linux

Install SDKMAN from bash
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

=== MacOS

Install SDKMAN from zsh or bash
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

=== Windows

Open a Windows PowerShell (PS) terminal (version 5.1 or later) and from the PS `C:\>` prompt, run:

.Step 1 - run Set-ExecutionPolicy
----
PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
----
.Step 2 - answer 'Y' when prompted to change the execution policy.
----
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\>
----

.Step 3 - run Invoke-RestMethod
----
PS C:\> Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
----

.Step 4 - wait for the installation to finish
----
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\>
----

Install Git and Git-Bash

[source,cmd]
----
scoop install git
----

Install MS Java 21 (OpenJDK)
----
scoop bucket add java
----

----
scoop install microsoft21-jdk
----

(Optionally) Install WinGetUI (aka UniGetUI) to apply future updates to the installed applications
----
scoop bucket add extras
----
----
scoop install extras/wingetui
----

== Build from Source

=== Linux

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== MacOS

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== Windows

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
build_and_run.cmd
----

== Example Benchmark Report

[source,text,options=nowrap]
----
Benchmark Report

SID       Name       RID Duration    #T       #S    #F  Avg TPS    Avg RT    50p RT   90p RT   99p RT   Max RT      Max RT Timestamp
0   Init
                     0   0.027    32       32       0  1185.2    0.137 ms   0.0 ms   0.1 ms   2.7 ms   2.7 ms   2024-07-08 06:36:31.599
                     -   0:00:00  32       32       0  1185.2    0.137 ms   0.0 ms   0.1 ms   2.7 ms   2.7 ms   2024-07-08 06:36:31.599
0   Max Throughput
                     0   60.0     81246662 81246662 0  1354111.0 0.000 ms   0.0 ms   0.0 ms   0.0 ms   0.1 ms   2024-07-08 06:39:12.700
                     -   0:01:00  81246662 81246662 0  1354111.0 0.000 ms   0.0 ms   0.0 ms   0.0 ms   0.1 ms   2024-07-08 06:39:12.700
0   Fixed Throughput
                     0   60.004   6008     6008     0  100.1     11.980 ms  10.2 ms  25.1 ms  28.3 ms  28.3 ms  2024-07-08 06:40:15.040
                     1   60.0     6010     6010     0  100.2     12.195 ms  11.1 ms  25.2 ms  28.3 ms  28.2 ms  2024-07-08 06:41:23.354
                     2   60.009   6011     6011     0  100.2     12.201 ms  11.1 ms  25.2 ms  28.3 ms  28.3 ms  2024-07-08 06:42:44.538
                     3   60.005   6012     6012     0  100.2     12.191 ms  10.2 ms  25.2 ms  28.3 ms  28.2 ms  2024-07-08 06:43:44.092
                     -   0:04:00  24041    24041    0  100.2     12.112 ms  10.2 ms  25.1 ms  28.2 ms  28.3 ms  2024-07-08 06:42:44.538
0   HTTP
                     0   30.198   149      149      0  4.9       44.610 ms  36.9 ms  54.3 ms  161.8 ms 271.9 ms 2024-07-08 06:44:48.103
                     1   30.0     150      150      0  5.0       36.388 ms  35.6 ms  39.7 ms  68.1 ms  78.7 ms  2024-07-08 06:45:35.298
                     2   30.196   153      153      0  5.1       35.733 ms  35.3 ms  38.9 ms  45.6 ms  47.8 ms  2024-07-08 06:45:53.100
                     -   0:01:30  452      452      0  5.0       38.762 ms  35.6 ms  41.0 ms  110.1 ms 271.9 ms 2024-07-08 06:44:48.103
0   Shutdown
                     0   1.609    16       16       0  9.9       100.160 ms 100.4 ms 100.4 ms 101.4 ms 101.0 ms 2024-07-08 06:46:22.014
                     -   0:00:01  16       16       0  9.9       99.936 ms  99.9 ms  99.9 ms  100.9 ms 101.0 ms 2024-07-08 06:46:22.014

----

== Appendix

=== Coordinated Omission

Tulip compensates for back-pressure from the system under test and adjusts the measured service times accordingly:

* https://redhatperf.github.io/post/coordinated-omission/

=== Kotlin Books

* https://www.manning.com/books/kotlin-in-action[Kotlin in Action, 1st Edition]
* https://typealias.com/start/[Kotlin: An Illustrated Guide]

=== Performance Engineering

* "Stop Rate Limiting! Capacity Management Done Right" by Jon Moore
** https://www.youtube.com/watch?v=m64SWl9bfvk