= Tulip (The Ultimate Load Injection Program)
:sectnums:
:toc:

== Dependencies

Install Git and JDK21 before building Tulip from source.

=== Linux

Install SDKMAN from bash (https://sdkman.io)
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

Install `w3m` (Debian, Ubuntu) to display reports
----
$ sudo apt install w3m
----

=== MacOS

Install SDKMAN from zsh or bash (https://sdkman.io)
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

Install `w3m` (MacOS) to display reports
----
$ brew install w3m
----

=== Windows

Open a Windows PowerShell (PS) terminal (version 5.1 or later) and from the PS `C:\>` prompt, run:

.Step 1 - run Set-ExecutionPolicy
----
PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
----
.Step 2 - answer 'Y' when prompted to change the execution policy.
----
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\>
----

.Step 3 - run Invoke-RestMethod
----
PS C:\> Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
----

.Step 4 - wait for the installation to finish
----
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\>
----

Install Git and Git-Bash

[source,cmd]
----
scoop install git
----

Install MS Java 21 (OpenJDK)
----
scoop bucket add java
----

----
scoop install microsoft21-jdk
----

(Optionally) Install WinGetUI (aka UniGetUI) to apply future updates to the installed applications
----
scoop bucket add extras
----
----
scoop install extras/wingetui
----

== Build from Source

=== Linux

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh  or ./build_and_run.sh --args="--config config.json"
----

=== MacOS

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== Windows

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
build_and_run.cmd
----

== Example Benchmark Reports

=== HTTP and other benchmarks

[source,text,options=nowrap]
----
SID          Name          RID Duration    #N        #S     #F  Avg TPS    Avg RT   Stdev   90p RT   99p RT   Max RT      Max RT Timestamp
0   Init (u:16 t:2)
                           0   0.035    32        32        0  914.3     0.187 ms   0.5 ms 0.4 ms   3.0 ms   3.0 ms   2024-07-13 10:40:06.502
                           -   0:00:00  32        32        0  914.3     0.186 ms   0.5 ms 0.4 ms   3.0 ms   3.0 ms   2024-07-13 10:40:06.502
0   Max TPS-a (u:16 t:2)
                           0   30.0     40651377  40651377  0  1355045.9 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-13 10:41:09.391
                           1   30.0     40916634  40916634  0  1363887.8 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-13 10:41:34.070
                           2   30.0     40500533  40500533  0  1350017.8 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-13 10:42:22.300
                           -   0:01:30  122068544 122068544 0  1356317.2 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-13 10:42:22.300
0   Max TPS-b (u:16 t:2)
                           0   30.0     29999995  29999995  0  999999.8  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-13 10:43:32.891
                           1   30.0     29999999  29999999  0  1000000.0 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-13 10:43:54.224
                           2   30.0     30000020  30000020  0  1000000.7 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-13 10:44:23.542
                           -   0:01:30  90000014  90000014  0  1000000.2 0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-13 10:43:54.224
0   Fixed TPS-a (u:16 t:2)
                           0   30.0     2999      2999      0  100.0     12.000 ms  8.1 ms 25.2 ms  28.2 ms  28.2 ms  2024-07-13 10:45:45.962
                           1   30.0     2998      2998      0  99.9      12.104 ms  8.2 ms 25.2 ms  28.3 ms  28.3 ms  2024-07-13 10:46:21.006
                           2   30.0     3001      3001      0  100.0     12.181 ms  8.4 ms 25.2 ms  28.3 ms  28.3 ms  2024-07-13 10:46:49.584
                           3   30.0     3003      3003      0  100.1     12.043 ms  8.1 ms 25.2 ms  28.2 ms  28.2 ms  2024-07-13 10:47:02.980
                           -   0:02:00  12001     12001     0  100.0     12.053 ms  8.2 ms 25.1 ms  28.2 ms  28.3 ms  2024-07-13 10:46:21.006
0   Fixed TPS-b (u:16 t:2)
                           0   30.0     3001      3001      0  100.0     10.164 ms  0.0 ms 10.2 ms  10.3 ms  11.5 ms  2024-07-13 10:48:01.773
                           1   30.0     3001      3001      0  100.0     10.165 ms  0.0 ms 10.2 ms  10.3 ms  10.3 ms  2024-07-13 10:48:28.681
                           2   30.0     3001      3001      0  100.0     10.168 ms  0.0 ms 10.2 ms  10.3 ms  10.5 ms  2024-07-13 10:49:16.887
                           3   30.0     3003      3003      0  100.1     10.165 ms  0.0 ms 10.2 ms  10.3 ms  10.3 ms  2024-07-13 10:49:53.773
                           -   0:02:00  12006     12006     0  100.0     10.137 ms  0.0 ms 10.2 ms  10.2 ms  11.5 ms  2024-07-13 10:48:01.773
0   HTTP-a (u:16 t:2)
                           0   30.0     246483    246483    0  8216.1    0.177 ms   0.0 ms 0.2 ms   0.3 ms   2.8 ms   2024-07-13 10:50:59.781
                           1   30.0     243769    243769    0  8125.6    0.179 ms   0.0 ms 0.2 ms   0.3 ms   2.5 ms   2024-07-13 10:51:01.863
                           2   30.0     243508    243508    0  8116.9    0.179 ms   0.0 ms 0.2 ms   0.2 ms   1.4 ms   2024-07-13 10:51:33.456
                           -   0:01:30  733760    733760    0  8152.9    0.179 ms   0.0 ms 0.2 ms   0.3 ms   2.8 ms   2024-07-13 10:50:59.781
0   HTTP-b (u:16 t:2)
                           0   30.0     37501     37501     0  1250.0    0.665 ms   0.1 ms 0.8 ms   0.9 ms   3.1 ms   2024-07-13 10:52:57.245
                           1   30.0     37501     37501     0  1250.0    0.643 ms   0.1 ms 0.8 ms   0.9 ms   3.1 ms   2024-07-13 10:53:32.158
                           2   30.0     37503     37503     0  1250.1    0.651 ms   0.1 ms 0.8 ms   0.9 ms   2.9 ms   2024-07-13 10:53:59.207
                           -   0:01:30  112505    112505    0  1250.1    0.651 ms   0.1 ms 0.8 ms   0.9 ms   3.1 ms   2024-07-13 10:52:57.245
0   Shutdown (u:16 t:2)
                           0   1.608    16        16        0  10.0      100.160 ms 0.2 ms 100.4 ms 101.3 ms 101.3 ms 2024-07-13 10:54:12.020
                           -   0:00:01  16        16        0  10.0      99.936 ms  0.2 ms 99.9 ms  100.9 ms 101.3 ms 2024-07-13 10:54:12.020

----

== Appendix

=== Coordinated Omission

Tulip compensates for back-pressure from the system under test and adjusts the measured service times accordingly:

* https://redhatperf.github.io/post/coordinated-omission/

=== Kotlin Books

* https://www.manning.com/books/kotlin-in-action[Kotlin in Action, 1st Edition]
* https://typealias.com/start/[Kotlin: An Illustrated Guide]

=== Performance Engineering

* "Stop Rate Limiting! Capacity Management Done Right" by Jon Moore
** https://www.youtube.com/watch?v=m64SWl9bfvk
