= Tulip (The Ultimate Load Injection Program)
:sectnums:
:toc:

== Dependencies

Install Git and JDK21 before building Tulip from source.

=== Linux

Install SDKMAN from bash
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

=== MacOS

Install SDKMAN from zsh or bash
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

=== Windows

Open a Windows PowerShell (PS) terminal (version 5.1 or later) and from the PS `C:\>` prompt, run:

.Step 1 - run Set-ExecutionPolicy
----
PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
----
.Step 2 - answer 'Y' when prompted to change the execution policy.
----
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\>
----

.Step 3 - run Invoke-RestMethod
----
PS C:\> Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
----

.Step 4 - wait for the installation to finish
----
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\>
----

Install Git and Git-Bash

[source,cmd]
----
scoop install git
----

Install MS Java 21 (OpenJDK)
----
scoop bucket add java
----

----
scoop install microsoft21-jdk
----

(Optionally) Install WinGetUI (aka UniGetUI) to apply future updates to the installed applications
----
scoop bucket add extras
----
----
scoop install extras/wingetui
----

== Build from Source

=== Linux

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== MacOS

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== Windows

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
build_and_run.cmd
----

== Results

[source,text,options=nowrap]
----
Benchmark Report

SID       Name       RID Duration    #T       #S    #F Avg TPS    Avg RT    90p RT   95p RT   99p RT   Max RT      Max RT Timestamp
0   Init
                     0   0.051    32       32       0  627.5    0.127 ms   0.1 ms   0.3 ms   2.5 ms   2.5 ms   2024-07-06 20:32:04.158
                     -   0:00:00  32       32       0  627.5    0.127 ms   0.1 ms   0.3 ms   2.5 ms   2.5 ms   2024-07-06 20:32:04.158
0   Max Throughput
                     0   60.0     49804461 49804461 0  830074.3 0.000 ms   0.0 ms   0.0 ms   0.0 ms   1.3 ms   2024-07-06 20:34:24.355
                     -   0:01:00  49804461 49804461 0  830074.3 0.000 ms   0.0 ms   0.0 ms   0.0 ms   1.3 ms   2024-07-06 20:34:24.355
0   Fixed Throughput
                     0   60.004   6001     6001     0  100.0    13.257 ms  26.2 ms  28.9 ms  33.5 ms  98.9 ms  2024-07-06 20:36:41.644
                     1   60.002   6004     6004     0  100.1    13.347 ms  26.2 ms  28.6 ms  32.3 ms  92.2 ms  2024-07-06 20:37:01.444
                     2   60.003   6010     6010     0  100.2    13.086 ms  25.9 ms  28.4 ms  32.9 ms  63.2 ms  2024-07-06 20:38:10.058
                     3   60.02    5999     5999     0  100.0    13.463 ms  26.1 ms  28.5 ms  32.5 ms  99.0 ms  2024-07-06 20:38:59.835
                     -   0:04:00  24014    24014    0  100.0    13.291 ms  25.0 ms  30.0 ms  30.0 ms  99.0 ms  2024-07-06 20:38:59.835
0   REST
                     0   30.015   148      148      0  4.9      85.541 ms  166.0 ms 231.0 ms 501.0 ms 941.7 ms 2024-07-06 20:40:44.000
                     1   30.006   150      150      0  5.0      58.633 ms  92.5 ms  143.7 ms 250.0 ms 447.7 ms 2024-07-06 20:40:49.653
                     2   30.01    152      152      0  5.1      44.507 ms  51.9 ms  69.5 ms  141.8 ms 141.8 ms 2024-07-06 20:41:23.002
                     -   0:01:30  450      450      0  5.0      62.716 ms  100.0 ms 150.0 ms 250.1 ms 941.7 ms 2024-07-06 20:40:44.000
0   Shutdown
                     0   1.733    16       16       0  9.2      100.000 ms 111.0 ms 111.0 ms 111.0 ms 111.0 ms 2024-07-06 20:41:55.225
                     -   0:00:01  16       16       0  9.2      100.000 ms 100.0 ms 100.0 ms 100.0 ms 111.0 ms 2024-07-06 20:41:55.225

----

== Appendix

=== Coordinated Omission

Tulip compensates for back-pressure from the system under test and adjusts the measured service times accordingly:

* https://redhatperf.github.io/post/coordinated-omission/

=== Kotlin Books

* https://www.manning.com/books/kotlin-in-action[Kotlin in Action, 1st Edition]
* https://typealias.com/start/[Kotlin: An Illustrated Guide]

=== Performance Engineering

* "Stop Rate Limiting! Capacity Management Done Right" by Jon Moore
** https://www.youtube.com/watch?v=m64SWl9bfvk