= Tulip (The Ultimate Load Injection Program)
:sectnums:
:toc:

== Dependencies

Install Git and JDK21 before building Tulip from source.

=== Linux

Install SDKMAN from bash (https://sdkman.io)
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

Install `w3m` (Debian, Ubuntu) to display reports
----
$ sudo apt install w3m
----

=== MacOS

Install SDKMAN from zsh or bash (https://sdkman.io)
----
$ curl -s "https://get.sdkman.io" | bash
----

----
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
----

----
$ sdk version
----

Install `w3m` (MacOS) to display reports
----
$ brew install w3m
----

=== Windows

Open a Windows PowerShell (PS) terminal (version 5.1 or later) and from the PS `C:\>` prompt, run:

.Step 1 - run Set-ExecutionPolicy
----
PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
----
.Step 2 - answer 'Y' when prompted to change the execution policy.
----
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\>
----

.Step 3 - run Invoke-RestMethod
----
PS C:\> Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
----

.Step 4 - wait for the installation to finish
----
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\>
----

Install Git and Git-Bash

[source,cmd]
----
scoop install git
----

Install MS Java 21 (OpenJDK)
----
scoop bucket add java
----

----
scoop install microsoft21-jdk
----

(Optionally) Install WinGetUI (aka UniGetUI) to apply future updates to the installed applications
----
scoop bucket add extras
----
----
scoop install extras/wingetui
----

== Build from Source

=== Linux

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh  or ./build_and_run.sh --args="--config config.json"
----

=== MacOS

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
sdk env install
./build_and_run.sh
----

=== Windows

----
git clone https://github.com/wfouche/Tulip.git
cd  Tulip
build_and_run.cmd
----

== Example Benchmark Reports

=== HTTP and other benchmarks

[source,text,options=nowrap]
----
SID          Name          RID  Avg TPS  Duration    #N        #S     #F   Avg RT   Stdev   90p RT   99p RT   Max RT      Max RT Timestamp
0   Init (u:16 t:2)
                           0   800.0     0.04     32        32        0  0.091 ms   0.3 ms 0.0 ms   1.7 ms   1.7 ms   2024-07-15 15:51:59.492
                           -   800.0     0:00:00  32        32        0  0.091 ms   0.3 ms 0.0 ms   1.7 ms   1.7 ms   2024-07-15 15:51:59.492
0   Max TPS-a (u:16 t:2)
                           0   1665467.9 30.0     49964037  49964037  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.3 ms   2024-07-15 15:53:15.206
                           1   1667727.6 30.0     50031828  50031828  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-15 15:53:41.205
                           2   1694676.9 30.0     50840307  50840307  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-15 15:54:07.007
                           -   1675957.5 0:01:30  150836172 150836172 0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.3 ms   2024-07-15 15:53:15.206
0   Max TPS-b (u:16 t:2)
                           0   999999.9  30.0     29999998  29999998  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-15 15:55:25.651
                           1   999999.9  30.0     29999998  29999998  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.3 ms   2024-07-15 15:55:56.344
                           2   1000000.0 30.0     29999999  29999999  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.1 ms   2024-07-15 15:56:20.129
                           -   999999.9  0:01:30  89999995  89999995  0  0.000 ms   0.0 ms 0.0 ms   0.0 ms   0.3 ms   2024-07-15 15:55:56.344
0   Fixed TPS-a (u:16 t:2)
                           0   100.0     30.0     3001      3001      0  12.098 ms  8.3 ms 25.2 ms  28.3 ms  28.3 ms  2024-07-15 15:57:25.505
                           1   100.0     30.0     3001      3001      0  12.228 ms  8.2 ms 24.3 ms  28.2 ms  28.2 ms  2024-07-15 15:58:10.754
                           2   100.0     30.0     3001      3001      0  12.085 ms  8.3 ms 25.2 ms  28.2 ms  28.2 ms  2024-07-15 15:58:19.769
                           3   100.0     30.0     3001      3001      0  11.969 ms  8.2 ms 24.3 ms  28.2 ms  28.2 ms  2024-07-15 15:58:45.324
                           -   100.0     0:02:00  12004     12004     0  12.065 ms  8.2 ms 25.1 ms  28.2 ms  28.3 ms  2024-07-15 15:57:25.505
0   Fixed TPS-b (u:16 t:2)
                           0   100.0     30.0     3001      3001      0  10.164 ms  0.0 ms 10.2 ms  10.3 ms  10.4 ms  2024-07-15 16:00:02.683
                           1   100.0     30.0     3001      3001      0  10.161 ms  0.0 ms 10.2 ms  10.3 ms  10.5 ms  2024-07-15 16:00:24.831
                           2   100.0     30.0     3001      3001      0  10.164 ms  0.0 ms 10.2 ms  10.3 ms  10.4 ms  2024-07-15 16:01:14.871
                           3   100.0     30.0     3001      3001      0  10.162 ms  0.0 ms 10.2 ms  10.3 ms  10.4 ms  2024-07-15 16:01:35.099
                           -   100.0     0:02:00  12004     12004     0  10.135 ms  0.0 ms 10.2 ms  10.2 ms  10.5 ms  2024-07-15 16:00:24.831
0   HTTP-a (u:16 t:2)
                           0   10318.8   30.0     309563    309563    0  0.189 ms   0.0 ms 0.2 ms   0.3 ms   2.1 ms   2024-07-15 16:02:40.101
                           1   10258.9   30.0     307767    307767    0  0.191 ms   0.0 ms 0.2 ms   0.3 ms   2.1 ms   2024-07-15 16:02:54.871
                           2   10183.7   30.0     305510    305510    0  0.192 ms   0.0 ms 0.2 ms   0.3 ms   1.3 ms   2024-07-15 16:03:24.922
                           -   10253.8   0:01:30  922840    922840    0  0.191 ms   0.0 ms 0.2 ms   0.3 ms   2.1 ms   2024-07-15 16:02:40.101
0   HTTP-b (u:16 t:2)
                           0   1250.0    30.0     37501     37501     0  0.658 ms   0.1 ms 0.8 ms   0.9 ms   3.3 ms   2024-07-15 16:04:31.867
                           1   1250.0    30.0     37501     37501     0  0.654 ms   0.1 ms 0.8 ms   0.9 ms   3.4 ms   2024-07-15 16:05:16.513
                           2   1250.0    30.0     37501     37501     0  0.650 ms   0.1 ms 0.8 ms   0.9 ms   3.4 ms   2024-07-15 16:05:29.938
                           -   1250.0    0:01:30  112503    112503    0  0.652 ms   0.1 ms 0.8 ms   0.9 ms   3.4 ms   2024-07-15 16:05:29.938
0   Shutdown (u:16 t:2)
                           0   9.9       1.61     16        16        0  100.352 ms 0.3 ms 100.9 ms 101.2 ms 101.2 ms 2024-07-15 16:06:05.048
                           -   9.9       0:00:01  16        16        0  100.128 ms 0.3 ms 100.4 ms 100.9 ms 101.2 ms 2024-07-15 16:06:05.048

----

== Appendix

=== Coordinated Omission

Tulip compensates for back-pressure from the system under test and adjusts the measured service times accordingly:

* https://redhatperf.github.io/post/coordinated-omission/

=== Kotlin Books

* https://www.manning.com/books/kotlin-in-action[Kotlin in Action, 1st Edition]
* https://typealias.com/start/[Kotlin: An Illustrated Guide]

=== Performance Engineering

* "Stop Rate Limiting! Capacity Management Done Right" by Jon Moore
** https://www.youtube.com/watch?v=m64SWl9bfvk
