/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
    // id("com.github.ben-manes.versions") version "0.53.0"
    id("org.jetbrains.kotlin.plugin.serialization") version "2.3.20"
    // id("org.jlleitschuh.gradle.ktlint") version "12.1.1"
    id("io.gitlab.arturbosch.detekt") version "1.23.6"
    jacoco
}

dependencies {
    implementation(project(":tulip-runtime"))
    implementation("org.jetbrains.kotlinx:kotlinx-html-jvm:0.12.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.0")
    implementation("org.hdrhistogram:HdrHistogram:2.2.2")
    implementation("org.asciidoctor:asciidoctorj:3.0.1")
    implementation("org.asciidoctor:asciidoctorj-diagram:3.2.0")
    implementation("org.asciidoctor:asciidoctorj-diagram-plantuml:1.2025.3")
}

tasks.jacocoTestReport {
    dependsOn(tasks.test) // tests are required to run before generating the report
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

application {
    // Define the main class for the application.
    mainClass = "io.github.tulipltt.tulip.report.TulipReportKt"
}
