/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.github.ajalt.clikt.core.*
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option

import io.github.wfouche.tulip.api.TulipApi
import io.github.wfouche.tulip.api.TulipUserFactory

private class TulipCli00 : CliktCommand() {
    private val configOpt by option("--config").default("")
    private val resultOpt by option("--result").default("")
    override fun run() {
        if (configOpt != "") {
            TulipApi.runTulip(configOpt, TulipUserFactory())
        } else if (resultOpt != "") {
                echo(resultOpt)
            TulipApi.createHtmlReport(resultOpt)
        }
    }
}

fun main(args: Array<String>) = TulipCli00().main(args)

