///usr/bin/env jbang "$0" "$@" ; exit $?

//DEPS dev.jbang:jash:0.0.3
//DEPS org.tomlj:tomlj:1.1.1
//DEPS org.python:jython-slim:2.7.4
//DEPS org.graalvm.python:jbang:24.2.1
//JAVA 17+
//NOINTEGRATIONS

import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.stream.Stream;
import java.nio.charset.StandardCharsets;
import dev.jbang.jash.Jash;
import org.tomlj.Toml;
import org.tomlj.TomlParseResult;
import org.tomlj.TomlTable;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.zip.GZIPInputStream;
import java.util.zip.GZIPOutputStream;

import org.python.util.jython;

public class python_jvm_tulip {

    private static final String appName = "python-jvm";
    private static final String appVersion = "__JBANG_SNAPSHOT_ID__/__JBANG_SNAPSHOT_TIMESTAMP__";

    private static void displayAppInfo() {
        String version = appVersion;
        if (appVersion.contains("JBANG_SNAPSHOT_ID")) {
            version = "0/2025-05-02T17:58:14";
        }
        System.out.println(appName + "/" + version);
    }

    /**
     * Compresses a string using GZIP compression.
     *
     * @param data The string to be compressed.
     * @return A byte array containing the compressed data.
     * @throws IOException if an I/O error occurs during compression.
     */
    public static byte[] compress(String data) throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream(data.length());
        GZIPOutputStream gzip = new GZIPOutputStream(bos);
        gzip.write(data.getBytes(StandardCharsets.UTF_8));
        gzip.close();
        byte[] compressedData = bos.toByteArray();
        bos.close();
        return compressedData;
    }

    /**
     * Decompresses a byte array that was compressed using GZIP.
     *
     * @param compressedData The byte array containing the compressed data.
     * @return The decompressed string.
     * @throws IOException if an I/O error occurs during decompression.
     */
    public static String decompress(byte[] compressedData) throws IOException {
        ByteArrayInputStream bis = new ByteArrayInputStream(compressedData);
        GZIPInputStream gzip = new GZIPInputStream(bis);
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        byte[] buffer = new byte[1024];
        int len;
        while ((len = gzip.read(buffer)) != -1) {
            bos.write(buffer, 0, len);
        }
        gzip.close();
        bis.close();
        bos.close();
        return bos.toString(StandardCharsets.UTF_8.name());
    }

    /**
     * Base64 encodes a byte array.
     *
     * @param data The byte array to be encoded.
     * @return A Base64 encoded string.
     */
    public static String encodeBase64(byte[] data) {
        return Base64.getEncoder().encodeToString(data);
    }

    /**
     * Decodes a Base64 encoded string back into a byte array.
     *
     * @param encodedData The Base64 encoded string.
     * @return A byte array containing the decoded data.
     */
    public static byte[] decodeBase64(String encodedData) {
        return Base64.getDecoder().decode(encodedData);
    }

    private static final String textJythonApp = """
            import org.python.util.PythonInterpreter;
            import java.util.Base64;
            import java.io.ByteArrayInputStream;
            import java.io.ByteArrayOutputStream;
            import java.io.IOException;
            import java.nio.charset.StandardCharsets;
            import java.util.Base64;
            import java.util.zip.GZIPInputStream;
            import java.util.zip.GZIPOutputStream;
            
            /**
             * The class provides a main method to run a Python script
             * embedded in a Java application.
             *
             * This class is generated by JBang from a Python script.
             */
            public class __CLASSNAME__ {
            
                /** The base64 encoded Python script to be executed. */
                public static String mainScriptTextBase64 = "__MAIN_SCRIPT__";

                /** Private constructor to prevent instantiation. */
                public __CLASSNAME__() {
                    // Private constructor to prevent instantiation
                }
                
                /**
                 * Decompresses a byte array that was compressed using GZIP.
                 *
                 * @param compressedData The byte array containing the compressed data.
                 * @return The decompressed string.
                 * @throws IOException if an I/O error occurs during decompression.
                 */
                public static String decompress(byte[] compressedData) throws IOException {
                    ByteArrayInputStream bis = new ByteArrayInputStream(compressedData);
                    GZIPInputStream gzip = new GZIPInputStream(bis);
                    ByteArrayOutputStream bos = new ByteArrayOutputStream();
                    byte[] buffer = new byte[1024];
                    int len;
                    while ((len = gzip.read(buffer)) != -1) {
                        bos.write(buffer, 0, len);
                    }
                    gzip.close();
                    bis.close();
                    bos.close();
                    return bos.toString(StandardCharsets.UTF_8.name());
                }
                    
                /**
                 * The main method that serves as the entry point for the application.
                 * It initializes the Python interpreter and executes the embedded script.
                 *
                 * @param args Command-line arguments passed to the application.
                 *
                 * @throws IOException if an I/O error occurs during decompression.
                 */
                public static void main(String... args) throws IOException {
                    String mainScriptFilename = "__MAIN_SCRIPT_FILENAME__";
                    String mainScript = "";
                    String pythonArgsScript = "";
                    for (String arg: args) {
                        if (pythonArgsScript.length() == 0) {
                            if (!arg.equals(mainScriptFilename)) {
                                pythonArgsScript += "'" + mainScriptFilename + "', ";
                            }
                        } else {
                            pythonArgsScript += ", ";
                        }
                        pythonArgsScript += "'" + arg + "'";
                    }
                    if (pythonArgsScript.length() == 0) {
                        pythonArgsScript = "'" + mainScriptFilename + "'";
                    }
                    pythonArgsScript = "import sys; sys.argv = [" + pythonArgsScript + "]";
                    {
                        byte[] decodedBytes = Base64.getDecoder().decode(mainScriptTextBase64);
                        String text = new String(decompress(decodedBytes));
                        mainScript = text;
                    }
                    {
                        // create Python interpreter object
                        PythonInterpreter pyInterp = new PythonInterpreter();
                        // initialize command-line args
                        pyInterp.exec(pythonArgsScript);
                        // run script
                        pyInterp.exec(mainScript);
                    }
                }
            }            
            """;

    public static final String textGraalpyApp = """
            import org.graalvm.polyglot.*;
            import java.util.Base64;
            
            public class __CLASSNAME__ {
            
                public static String mainScriptTextBase64 = "__MAIN_SCRIPT__";
            
                public static void main(String... args) {
                    String mainScriptFilename = "__MAIN_SCRIPT_FILENAME__";
                    String mainScript = "";
                    String pythonArgsScript = "";
                    for (String arg: args) {
                        if (pythonArgsScript.length() == 0) {
                            if (!arg.equals(mainScriptFilename)) {
                                pythonArgsScript += "'" + mainScriptFilename + "', ";
                            }
                        } else {
                            pythonArgsScript += ", ";
                        }
                        pythonArgsScript += "'" + arg + "'";
                    }
                    if (pythonArgsScript.length() == 0) {
                        pythonArgsScript = "'" + mainScriptFilename + "'";
                    }
                    pythonArgsScript = "import sys; sys.argv = [" + pythonArgsScript + "]";
                    {
                        byte[] decodedBytes = Base64.getDecoder().decode(mainScriptTextBase64);
                        String text = new String(decodedBytes);
                        mainScript = text;
                    }
                    {
                        try (var context = Context.newBuilder().option("python.EmulateJython", "__EMJ__").allowAllAccess(__AAA__).build()) {
                            Source sourceArgs = Source.create("python", pythonArgsScript);
                            Value result = context.eval(sourceArgs);
                            Source sourceMain = Source.create("python", mainScript);
                            result = context.eval(sourceMain);
                        }
                     }
                }
            }
            """;

    public static void main(String[] args) throws IOException {
        List<String> deps = new ArrayList<>();
        String jythonVersion = "2.7.4";
        String graalpyVersion = "";
        String graalpyAllowAllAccess = "true";
        String graalpyEmulateJython = "false";
        String javaVersion = "21";
        String javaRuntimeOptions = "";
        String jbangIntegrations = "true";
        String lineSep = "\n"; // String.valueOf((char) 10);
        boolean debug = false;
        boolean keepJava = false;

        displayAppInfo();

        // --keep-java <script-name>.py arg1 arg2, arg3 ...
        if (args.length > 1 && args[0].equals("--keep-java")) {
            keepJava = true;
            String[] newArgs = new String[args.length - 1];
            for (int i = 1; i < args.length; i++) {
                newArgs[i-1] = args[i];
            }
            args = newArgs;
        }

        // Invoke the Jython interpreter if no Python script file is specified, or Jython command-line options are specified
        if (args.length == 0 || (args.length > 0 && args[0].substring(0,1).equals("-"))) {
            jython.main(args);
            System.exit(0);
        }

        String scriptFilename = args[0];
        String javaClassname = new File(scriptFilename).getName().replace(".", "_");
        String javaFilename = javaClassname + ".java";

        // Parse PEP 723 text block
        {
            StringBuffer tomlText = new StringBuffer("");
            {
                List<String> lines = Files.readAllLines(Paths.get(scriptFilename));
                boolean found = false;
                for (String line: lines) {
                    if (line.startsWith("# /// jbang")) {
                        found = true;
                    }
                    else if (line.startsWith("# ///")) {
                        found = false;
                        break;
                    } else if (line.startsWith("# ")) {
                        if (found) {
                            if (tomlText.length() == 0) {
                                tomlText.append(line.substring(2));
                            } else {
                                tomlText.append(lineSep + line.substring(2));
                            }
                        }
                    }
                }
            }
            TomlParseResult tpr = Toml.parse(tomlText.toString());
            // [python-jvm]
            TomlTable pythonjvmTable = tpr.getTable("python-jvm");
            if (pythonjvmTable != null) {
                if (pythonjvmTable.isBoolean("debug")) {
                    debug = pythonjvmTable.getBoolean("debug");
                }
            }
            if (debug) {
                System.out.println("[debug] python-jvm init " + javaFilename + " from " + scriptFilename);
            }
            if (debug) {
                System.out.println("");
                System.out.println("[ -----------------jbang-config-begin-------------------- ]");
                System.out.println("");
                System.out.println(tpr.toToml());
                System.out.println("[ -----------------jbang-config-end---------------------- ]");
                System.out.println("");
            }
            if (tpr.isString("requires-jython")) {
                jythonVersion = tpr.getString("requires-jython");
            }
            if (tpr.isString("requires-graalpy")) {
                graalpyVersion = tpr.getString("requires-graalpy");
                // [graalpy]
                TomlTable graalpyTable = tpr.getTable("graalpy");
                if (graalpyTable != null) {
                    Boolean allowAllAccess = graalpyTable.getBoolean("allowAllAccess");
                    if (allowAllAccess != null && allowAllAccess.equals(Boolean.TRUE) ) {
                        graalpyAllowAllAccess = "true";
                    }
                    Boolean emulateJython = graalpyTable.getBoolean("emulateJython");
                    if (emulateJython != null && emulateJython.equals(Boolean.TRUE) ) {
                        graalpyEmulateJython = "true";
                    }
                }
            }
            if (tpr.isString("requires-java")) {
                javaVersion = tpr.getString("requires-java");
            }
            // dependencies
            for (Object e : tpr.getArrayOrEmpty("dependencies").toList()) {
                String dep = (String) e;
                deps.add(dep);
            }
            // [java]
            TomlTable javaTable = tpr.getTable("java");
            if (javaTable != null) {
                String runtimeOptions = javaTable.getString("runtime-options");
                if (runtimeOptions != null) {
                    javaRuntimeOptions = runtimeOptions;
                }
            }
            // [jbang]
            TomlTable jbangTable = tpr.getTable("jbang");
            if (jbangTable != null) {
                Boolean integrations = jbangTable.getBoolean("integrations");
                if (integrations != null && integrations.equals(Boolean.FALSE)) {
                    jbangIntegrations = "false";
                }
            }
        }

        String dep = "org.python:jython-slim:" + jythonVersion;
        if (graalpyVersion.length() > 0) {
            dep = "org.graalvm.python:jbang:" + graalpyVersion;
        }
        deps.add(dep);

        byte[] data0 = Files.readAllBytes(Paths.get(scriptFilename));
        String data1 = new String(data0, StandardCharsets.UTF_8);
        data1 = data1.replace("\r", "");
        String scriptFileTextB64 = Base64.getEncoder().encodeToString(compress(data1));
        //System.out.println(data1.length());
        //System.out.println(scriptFileTextB64.length());

        try (BufferedWriter jf = new BufferedWriter(new FileWriter(javaFilename))) {
            // jf.write("///usr/bin/env jbang \"$0\" \"$@\" ; exit $?" + lineSep + lineSep);
            jf.write("// spotless:off" + lineSep);
            for (String dependency : deps) {
                jf.write("//DEPS " + dependency + lineSep);
            }
            jf.write("//JAVA " + javaVersion + lineSep);
            if (javaRuntimeOptions.length() > 0) {
                jf.write("//RUNTIME_OPTIONS " + javaRuntimeOptions + lineSep);
            }
            if (jbangIntegrations.equals("false")) {
                jf.write("//NOINTEGRATIONS" + lineSep);
            }
            jf.write("// spotless:on" + lineSep + lineSep);
            String text = textJythonApp;
            if (graalpyVersion.length() > 0) {
                text = textGraalpyApp;
                text = text.replace("__EMJ__", graalpyEmulateJython);
                text = text.replace("__AAA__", graalpyAllowAllAccess);
            }
            String jtext = text.replace("__CLASSNAME__", javaClassname)
                               .replace("__MAIN_SCRIPT__", scriptFileTextB64)
                               .replace("__MAIN_SCRIPT_FILENAME__", scriptFilename);
            jf.write(jtext);
        }

        // register javaFilename to be deleted when the JVM exits
        if (!keepJava) {
            new File(javaFilename).deleteOnExit();
        }

        // jbang run <script>_py.java param1 param2 ...
        {
            StringBuffer params = new StringBuffer("run");

            params.append(" " + javaFilename);
            for (int i = 1; i < args.length; i++) {
                params.append(" " + args[i]);
            }
            //if (debug) System.out.println("[debug] jbang " + params.toString());
            String ext = System.getProperty("os.name").toLowerCase().startsWith("win") ? ".cmd" : "";
            var jargs = params.toString().split("\\s+");
            try (Stream<String> ps = Jash.start("jbang" + ext, jargs).stream()) {
                    ps.forEach(System.out::println);
            }
        }
    }
}
