= Tulip

== Introduction

TBD - the documentation journey has just started.


[appendix]

== Stacked Bar Chart

[mermaid,mermaid.png]
----
gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1, 20d
    section Another
    Task in sec      :2014-01-12, 12d
    another task     :24d
----

[vegalite,vegalite.png]
----
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal", "axis": {"labelAngle": 0}},
    "y": {"field": "b", "type": "quantitative"}
  }
}
----

[vega,vega.png]
----
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "A basic stacked bar chart example.",
  "width": 500,
  "height": 200,
  "padding": 5,

  "data": [
    {
      "name": "table",
      "values": [
        {"x": 0, "y": 28, "c": 0}, {"x": 0, "y": 55, "c": 1},
        {"x": 1, "y": 43, "c": 0}, {"x": 1, "y": 91, "c": 1},
        {"x": 2, "y": 81, "c": 0}, {"x": 2, "y": 53, "c": 1},
        {"x": 3, "y": 19, "c": 0}, {"x": 3, "y": 87, "c": 1},
        {"x": 4, "y": 52, "c": 0}, {"x": 4, "y": 48, "c": 1},
        {"x": 5, "y": 24, "c": 0}, {"x": 5, "y": 49, "c": 1},
        {"x": 6, "y": 87, "c": 0}, {"x": 6, "y": 66, "c": 1},
        {"x": 7, "y": 17, "c": 0}, {"x": 7, "y": 27, "c": 1},
        {"x": 8, "y": 68, "c": 0}, {"x": 8, "y": 16, "c": 1},
        {"x": 9, "y": 49, "c": 0}, {"x": 9, "y": 15, "c": 1}
      ],
      "transform": [
        {
          "type": "stack",
          "groupby": ["x"],
          "sort": {"field": "c"},
          "field": "y"
        }
      ]
    }
  ],

  "scales": [
    {
      "name": "x",
      "type": "band",
      "range": "width",
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true, "zero": true,
      "domain": {"data": "table", "field": "y1"}
    },
    {
      "name": "color",
      "type": "ordinal",
      "range": "category",
      "domain": {"data": "table", "field": "c"}
    }
  ],

  "axes": [
    {"orient": "bottom", "scale": "x", "zindex": 1},
    {"orient": "left", "scale": "y", "zindex": 1}
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"scale": "x", "field": "x"},
          "width": {"scale": "x", "band": 1, "offset": -1},
          "y": {"scale": "y", "field": "y0"},
          "y2": {"scale": "y", "field": "y1"},
          "fill": {"scale": "color", "field": "c"}
        },
        "update": {
          "fillOpacity": {"value": 1}
        },
        "hover": {
          "fillOpacity": {"value": 0.5}
        }
      }
    }
  ]
}
----



== Sample JSON Report

The performance results of each benchmark step that is executed during the running of a benchmark suite of tests, is saved as a single line of JSON text in an output file. 
Below we pretty print one such line of JSON text. The first section of information is a summary of how well the system under test (SUT) performed. 
The user_actions section  reports performance information for the individual operations (actions) that were executed. 
For example, globally we can see that 80 actions in total were executed (num_actions=80).
However, looking at the breakdown of this information per user_action we see that
action "0" was executed 40 times and action "7" was also executed 40 times.

.print(json.dumps(json.loads(s),indent=2))
[source,json]
----
{
  "duration": 16.005,
  "test_id": 0,
  "test_phase": "Main",
  "row_id": 0,
  "num_users_active": 1,
  "num_users": 40,
  "num_threads": 4,
  "test_name": "Test0 (Initialize)",
  "test_begin": "2020-03-31T15:14:46.162186600",
  "test_end": "2020-03-31T15:15:02.178890700",
  "avg_cpu_process": 1.155,
  "avg_cpu_system": 26.130000000000003,
  "num_actions": 80,     // <.>
  "num_success": 80,
  "num_failed": 0,
  "avg_tps": 4.99843798812871,
  "avg_rt": 0.09275,
  "sdev_rt": 0.2718293352454808,
  "min_rt": 0.032,
  "max_rt": 2.545,
  "max_rt_ts": "2020-03-31T15:14:46.375441900",
  "percentiles_rt": {
    "50.0": 0.055857142857142855,
    "90.0": 0.09433333333333332,
    "95.0": 0.111,
    "99.0": 2.3498000000000014
  },
  "user_actions": {
    "0": {
      "num_actions": 40,  // <.>
      "num_success": 40,
      "num_failed": 0,
      "avg_tps": 2.499218994064355,
      "avg_rt": 0.120875,
      "sdev_rt": 0.38152963105766763,
      "min_rt": 0.032,
      "max_rt": 2.545,
      "max_rt_ts": "2020-03-31T15:14:46.375441900",
      "percentiles_rt": {
        "50.0": 0.056,
        "90.0": 0.095,
        "95.0": 0.111,
        "99.0": 2.545
      }
    },
    "7": {
      "num_actions": 40,  // <.>
      "num_success": 40,
      "num_failed": 0,
      "avg_tps": 2.499218994064355,
      "avg_rt": 0.064625,
      "sdev_rt": 0.02520881542238746,
      "min_rt": 0.034,
      "max_rt": 0.126,
      "max_rt_ts": "2020-03-31T15:15:00.572516100",
      "percentiles_rt": {
        "50.0": 0.05566666666666666,
        "90.0": 0.092,
        "95.0": 0.111,
        "99.0": 0.126
      }
    }
  }
}
----
. num_actions (globally) = 80
. num_action (action_id=0) = 40
. num_action (action_id=7) = 40
