/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "io.github.wfouche.tulip"
version = "1.0.0-SNAPSHOT"

plugins {
    id("org.jreleaser").version("1.14.0")
    id("kotlinx-serialization")
}
