/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.lib

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.*

class TulipLibTest1 {
    @Test fun testConstructor() {
        assertEquals(0, 0)
    }

}
