/*
 * This source file was generated by the Gradle 'init' task
 */

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun appHasAGreeting() {
        val x = 1
        assertTrue(x == 1)
    }
}
