/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class TulipTest1 {
    @Test fun testGetMessage() {
        assertEquals("a", "a")
    }
}
