name: Validate the Tulip Runtime
on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.8'
          distribution: 'temurin'
      - name: Install w3m
        run: sudo apt-get -y install w3m
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Publish package to local staging directory
        run: ./gradlew :tulip-runtime:publish
      - name: Sign and Deploy Maven Artifacts
        env:
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :tulip-runtime:jreleaserDeploy --dryrun -DaltDeploymentRepository=local::file:./tulip-runtime/build/staging-deploy --stacktrace
      - name: List all Maven Artifacts
        run: find ./tulip-runtime/build/staging-deploy -print | sort
      - name: Run Tulip test benchmark at 100 TPS
        run: ./gradlew -q :tulip-main:run --args="--config benchmark_config_test.jsonc"
      - name: Display the Tulip HTML report
        run: w3m -dump -cols 200 ./tulip-main/benchmark_report.html